server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
temp:
  directory:
    path: temp
resource:
  ffmpeg:
    path: /FFmpeg
  ffprobe:
    path: /FFprobe